const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '../public/images');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'photo1.webp'), Buffer.from(require('./img0.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo10.webp'), Buffer.from(require('./img1.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo2.webp'), Buffer.from(require('./img2.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo3.webp'), Buffer.from(require('./img3.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo4.webp'), Buffer.from(require('./img4.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo5.webp'), Buffer.from(require('./img5.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo6.webp'), Buffer.from(require('./img6.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo7.webp'), Buffer.from(require('./img7.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo8.webp'), Buffer.from(require('./img8.cjs'), 'base64'));
fs.writeFileSync(path.join(dir, 'photo9.webp'), Buffer.from(require('./img9.cjs'), 'base64'));
